Oscillation : "Standard"
Binning : "3DEZ"
Livetime: 1.
BestFit: {
  s2t12: 0.303,
  s2t13: 0.022,
  s2t23: 0.572, 
  m21: 7.41e-5, 
  m31: 2.511e-3, 
  dCP: 1.36
}
FullChiSqFn: "ChiSq_with_penalty_with_error"
StatChiSqFn: "ChiSq_only_no_prior"

DataFitting: {
  do_data_fitting: false,
  # data_dir: "../datafiles/ORCA/",
  data_parquet_file: "../datafiles/ORCA/ORCA_data_dataverse.parquet"
}

FluxSyst : {
  FluxNormalization_Below1GeV: 1,
  FluxNormalization_Above1GeV: 1,
  FluxTilt:  1,
  NuNubarRatio: 1,
  FlavorRatio: 1,
  ZenithFluxUp: 1,
  ZenithFluxDown: 1
}

DetSyst : {
  IceAbsorption: 0, 
  IceScattering: 0, 
  OffSet: 0,
  OptEffHeadon: 0, 
  OptEffLateral: 0,
  OptEffOverall: 0, 
  CoinFraction: 0
}

XsecSyst: {
  XSecNuTau : 0, 
  NCoverCC : 0, 
  AxialMass : 0, 
  NCHad : 0, 
  DIS: 0, 
  CCQE: 0, 
  CCQENuBarNu: 0, 
  CCQEMuE: 0
}