Experiment : 'ORCA'
filepath : '../datafiles/ORCA/ORCA_MC.parquet'
Oscillation : "Sterile"
Binning : "3DEZ"
FullChiSqFn: "ChiSq_with_penalty_with_error"
StatChiSqFn: "ChiSq_only_no_prior"
BestFit: {
  s2t12: 0.304,
  s2t13: 0.022,
  s2t23: 0.572,
  s2t14: 0,
  s2t24: 0,
  s2t34: 0, 
  m21: 7.42e-5,
  m31: 2.5e-3,
  m41: 0,
  dCP: 1.3,
  dCP24: 0
}

FluxSyst : {
  FluxNormalization_Below1GeV: 1,
  FluxNormalization_Above1GeV: 1,
  FluxTilt: 1,
  NuNubarRatio: 1,
  FlavorRatio: 1,
  ZenithFluxUp: 1,
  ZenithFluxDown: 1
}

DetSyst : {
  IceAbsorption: 0, 
  IceScattering: 0, 
  OffSet: 0, 
  OptEffHeadon: 0, 
  OptEffLateral: 0,
  OptEffOverall: 0, 
  CoinFraction: 0
}

XsecSyst: {
  XSecNuTau : 1, 
  NCoverCC : 1, 
  AxialMass : 1, 
  NCHad : 1, 
  DIS: 0, 
  CCQE: 0, 
  CCQENuBarNu: 0, 
  CCQEMuE: 0
}